# services:
#   app:
#     build:
#       context: .
#     image: app-name
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development
#     develop:
#       watch:
#         - action: sync
#           path: ./app
#           target: /app
#         - action: rebuild
#           path: package.json

# DB configuration

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: myPassword
    ports:
      - "5432:5432"
